In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
data =pd.read_csv(r"C:\Users\sonia\Downloads\archive (15)\udemy_courses.csv")

In [7]:
data.head()

course_id                                       course_title  \
0    1070968                 Ultimate Investment Banking Course   
1    1113822  Complete GST Course & Certification - Grow You...   
2    1006314  Financial Modeling for Business Analysts and C...   
3    1210588  Beginner to Pro - Financial Analysis in Excel ...   
4    1011058       How To Maximize Your Profits Trading Options   

                                                 url  is_paid  price  \
0  https://www.udemy.com/ultimate-investment-bank...     True    200   
1      https://www.udemy.com/goods-and-services-tax/     True     75   
2  https://www.udemy.com/financial-modeling-for-b...     True     45   
3  https://www.udemy.com/complete-excel-finance-c...     True     95   
4  https://www.udemy.com/how-to-maximize-your-pro...     True    200   

   num_subscribers  num_reviews  num_lectures               level  \
0             2147           23            51          All Levels   
1             2792          923           274          All Levels   
2             2174           74            51  Intermediate Level   
3             2451           11            36          All Levels   
4             1276           45            26  Intermediate Level   

   content_duration   published_timestamp           subject  
0               1.5  2017-01-18T20:58:58Z  Business Finance  
1              39.0  2017-03-09T16:34:20Z  Business Finance  
2               2.5  2016-12-19T19:26:30Z  Business Finance  
3               3.0  2017-05-30T20:07:24Z  Business Finance  
4               2.0  2016-12-13T14:57:18Z  Business Finance

In [9]:
data.shape

(3678, 12)

In [13]:
data.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [15]:
data.duplicated().any()

True

In [17]:
data[data.duplicated()]

course_id                                       course_title  \
787      837322  Essentials of money value: Get a financial Life !   
788     1157298  Introduction to Forex Trading Business For Beg...   
894     1035638                 Understanding Financial Statements   
1100    1084454                  CFA Level 2- Quantitative Methods   
1473     185526                             MicroStation - Células   
2561      28295  Learn Web Designing & HTML5/CSS3 Essentials in...   

                                                    url  is_paid  price  \
787    https://www.udemy.com/essentials-of-money-value/     True     20   
788   https://www.udemy.com/introduction-to-forex-tr...     True     20   
894   https://www.udemy.com/understanding-financial-...     True     25   
1100  https://www.udemy.com/cfa-level-2-quantitative...     True     40   
1473        https://www.udemy.com/microstation-celulas/     True     20   
2561  https://www.udemy.com/build-beautiful-html5-we...     True     75   

      num_subscribers  num_reviews  num_lectures           level  \
787                 0            0            20      All Levels   
788                 0            0            27  Beginner Level   
894                 0            0            10      All Levels   
1100                0            0            35      All Levels   
1473                0            0             9  Beginner Level   
2561            43285          525            24      All Levels   

      content_duration   published_timestamp           subject  
787           0.616667  2016-05-16T18:28:30Z  Business Finance  
788           1.500000  2017-04-23T16:19:01Z  Business Finance  
894           1.000000  2016-12-15T14:56:17Z  Business Finance  
1100          5.500000  2017-07-02T14:29:35Z  Business Finance  
1473          0.616667  2014-04-15T21:48:55Z    Graphic Design  
2561          4.000000  2013-01-03T00:55:31Z   Web Development

In [19]:
data.duplicated().sum()

6

In [29]:
data=data.drop_duplices()

AttributeError: 'DataFrame' object has no attribute 'drop_duplices'

In [31]:
data.duplicated().any()

False

## popularity based recommendation system

In [36]:
data.columns

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'published_timestamp', 'subject'],
      dtype='object')

In [62]:
def pop_rem(data):
    data['pop_score']=0.6*data['num_subscribers']+0.4*data['num_reviews']
    df_sorted=data.sort_values(by='pop_score',ascending=False)[['course_title','pop_score']].head()
    return df_sorted

In [64]:
pop_rem(data)

course_title  pop_score
2827               Learn HTML5 Programming From Scratch   164805.4
3032                     Coding for Entrepreneurs Basic    96729.0
3230                         The Web Developer Bootcamp    83928.4
3232              The Complete Web Developer Course 2.0    77672.0
2783  Build Your First Website in 1 Week with HTML5 ...    74544.2

 ## Content based recommendation system

In [67]:
data.head(1)

course_id                        course_title  \
0    1070968  Ultimate Investment Banking Course   

                                                 url  is_paid  price  \
0  https://www.udemy.com/ultimate-investment-bank...     True    200   

   num_subscribers  num_reviews  num_lectures       level  content_duration  \
0             2147           23            51  All Levels               1.5   

    published_timestamp           subject  pop_score  
0  2017-01-18T20:58:58Z  Business Finance     1297.4

In [77]:
# first we need to remove stopwords and special characters in the course-title.
# note:for sentimental analysis we do not remove stopwords
# we need to import neattext.function

! pip3 install neattext


   ---------------------------------------- 0.0/114.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/114.7 kB ? eta -:--:--
   ---------- ---------------------------- 30.7/114.7 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 114.7/114.7 kB 1.3 MB/s eta 0:00:00


In [79]:
import neattext.functions as nfx

In [81]:
data['course_title']

0                      Ultimate Investment Banking Course
1       Complete GST Course & Certification - Grow You...
2       Financial Modeling for Business Analysts and C...
3       Beginner to Pro - Financial Analysis in Excel ...
4            How To Maximize Your Profits Trading Options
                              ...                        
3673    Learn jQuery from Scratch - Master of JavaScri...
3674    How To Design A WordPress Website With No Codi...
3675                        Learn and Build using Polymer
3676    CSS Animations: Create Amazing Effects on Your...
3677    Using MODX CMS to Build Websites: A Beginner's...
Name: course_title, Length: 3672, dtype: object

In [83]:
data['course_title']=data['course_title'].apply(nfx.remove_stopwords)

In [149]:
data['title_subject']=data['course_title']+''+data['subject']

In [87]:
data['course_title']=data['course_title'].apply(nfx.remove_special_characters)

In [151]:
data['title_subject']

0       Ultimate Investment Banking CourseBusiness Fin...
1       Complete GST Course  Certification  Grow Pract...
2       Financial Modeling Business Analysts Consultan...
3       Beginner Pro  Financial Analysis Excel 2017Bus...
4        Maximize Profits Trading OptionsBusiness Finance
                              ...                        
3673    Learn jQuery Scratch  Master JavaScript librar...
3674       Design WordPress Website CodingWeb Development
3675                   Learn Build PolymerWeb Development
3676    CSS Animations Create Amazing Effects WebsiteW...
3677    MODX CMS Build Websites Beginners GuideWeb Dev...
Name: title_subject, Length: 3672, dtype: object

In [89]:
data['course_title']

0                      Ultimate Investment Banking Course
1       Complete GST Course  Certification  Grow Practice
2        Financial Modeling Business Analysts Consultants
3             Beginner Pro  Financial Analysis Excel 2017
4                        Maximize Profits Trading Options
                              ...                        
3673      Learn jQuery Scratch  Master JavaScript library
3674                      Design WordPress Website Coding
3675                                  Learn Build Polymer
3676        CSS Animations Create Amazing Effects Website
3677              MODX CMS Build Websites Beginners Guide
Name: course_title, Length: 3672, dtype: object

In [157]:
# now lets import count vectorizer.now we will set your max_features to 3000 in your corpus
# count vec is a text processing tool, used to collect the text documents and covert into numerical it is represent in form of matrixs
from sklearn.feature_extraction.text import CountVectorizer

In [159]:
cv= CountVectorizer(max_features=3000)
vectors=cv.fit_transform(data['title_subject']).toarray()

In [161]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [163]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [165]:
vectors.shape

(3672, 3000)

In [167]:
# calculation of cosine similarity with all vectors
# cosine similarity(A,B)=(A.B)/|A|.|B|
# 0 indices no similarity b/w 2 variables
# 1 indices similarity b/w 2 variables

from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
print(similarity)

[[1.         0.16903085 0.2        ... 0.         0.         0.        ]
 [0.16903085 1.         0.16903085 ... 0.         0.         0.        ]
 [0.2        0.16903085 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.18898224 0.40824829]
 [0.         0.         0.         ... 0.18898224 1.         0.15430335]
 [0.         0.         0.         ... 0.40824829 0.15430335 1.        ]]


In [169]:
similarity.shape

(3672, 3672)

In [171]:
# similarity of 1st course with rest of courses
similarity[0]

array([1.        , 0.16903085, 0.2       , ..., 0.        , 0.        ,
       0.        ])

In [173]:
#enumerate is used to find the index value,but in above it is found that sorting is perform on index it should be performed on similarities so key is used. 
sorted(enumerate(similarity[0]),reverse=True,key=lambda x:x[1])[1:6]

[(417, 0.6),
 (39, 0.5477225575051662),
 (657, 0.5477225575051662),
 (1066, 0.5477225575051662),
 (227, 0.5070925528371099)]

In [175]:
# index 39 should be converted to course title

data.iloc[39]['course_title']

'Complete Investment Banking Course 2017'

In [177]:
data.iloc[39]['course_title']

'Complete Investment Banking Course 2017'

In [179]:
def content_recomm(course):
           course_index=data[data['course_title']==course].index[0]
           sim=similarity['course_title']
           course_list=sorted(enumerate(similarity[0]),reverse=True,key=lambda x:x[1])[1:6]
           for i in course_list:
               print(data.iloc[i[0]]['course_title'])

In [181]:
content_recomm("Ultimate Investment Banking Course")

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices